#pragma libcall MLMMULibBase MLMMU_AllocMem 1E 91003
#pragma libcall MLMMULibBase MLMMU_FreeMem 24 901
#pragma libcall MLMMULibBase MLMMU_FindMemBlk 2A 901
#pragma libcall MLMMULibBase MLMMU_FindMem 30 901
#pragma libcall MLMMULibBase MLMMU_PleaseFree 36 001
#pragma libcall MLMMULibBase MLMMU_AvailMem 3C 101
#pragma libcall MLMMULibBase MLMMU_GetMemList 42 0
#pragma libcall MLMMULibBase MLMMU_GetMemStat 48 901
#pragma libcall MLMMULibBase MLMMU_SetMemStat 4E 9002
#pragma libcall MLMMULibBase MLMMU_OwnMemBlk 54 901
#pragma libcall MLMMULibBase MLMMU_DisOwnMemBlk 5A 901
#pragma libcall MLMMULibBase MLMMU_FlushMem 60 101
#pragma libcall MLMMULibBase MLMMU_OpenMsgQueue 66 0
#pragma libcall MLMMULibBase MLMMU_CloseMsgQueue 6C 0
#pragma libcall MLMMULibBase MLMMU_AddMsgToQueue 72 0802
#pragma libcall MLMMULibBase MLMMU_GetQueueList 78 0
#pragma libcall MLMMULibBase MLMMU_ReallyFlushMem 7E 101
