/******** MENUDEFINES.H ********/

#define DA_MENU					0
enum {	DA_ABOUT };

#define FILE_MENU				1
enum {	FILE_NEW, FILE_OPEN, FILE_CLOSE, FILE_SAVE, FILE_SAVEAS,
				FILE_PAGESETUP, FILE_PRINT, FILE_QUIT };

#define EDIT_MENU				2
enum { 	EDIT_UNDO, EDIT_CUT, EDIT_COPY, EDIT_PASTE, EDIT_CLEAR,
				EDIT_SELECTALL, EDIT_DISTRI, EDIT_DUPLI };

#define FONT_MENU				3
enum {	FONT_TYPE, FONT_STYLE, FONT_COLOR, FONT_PLAIN, FONT_BOLD, FONT_ITALIC, FONT_UNDERLINE };

#define PMISC_MENU			4
enum {	PMISC_IMPORT, PMISC_DEFINE, PMISC_PALETTE, PMISC_SCREENSIZE,
				PMISC_LINK, PMISC_REMAP, PMISC_SPECIALS, PMISC_TRANSITIONS, PMISC_INTERACTIVE };

#define SCREEN_MENU			5
enum {	SCREEN_PAGE, SCREEN_SCRIPT, SCREEN_PREFS };

#define XFER_MENU				3
enum {	XFER_UPLOAD, XFER_DOWNLOAD };

#define SMISC_MENU			4
enum {	SMISC_SHOWPROG, SMISC_LOCALEVENTS, SMISC_TWEAKER, SMISC_SCRIPTMANAGER, SMISC_VARPATH };

/******** E O F ********/
