; file:asi:toccata/toccata_lib.i
;
; generated by FixFD v1.0
;
; Bias = 30
;
_LVOT_NextFrequency	equ -30
_LVOT_FindFrequency	equ -36
_LVOT_SetPart	equ -42
_LVOT_GetPart	equ -48
_LVOT_Capture	equ -54
_LVOT_Playback	equ -60
_LVOT_Pause	equ -66
_LVOT_Stop	equ -72
_LVOT_StartLevel	equ -78
_LVOT_StopLevel	equ -84
_LVOT_Expand	equ -90
_LVOT_SaveSettings	equ -96
_LVOT_LoadSettings	equ -102
_LVOT_RawPlayback	equ -108
